- hosts: lobby
  collections:
    - triplea.infra
  vars_files:
    - vars.yml
  roles:
    - triplea.infra.postgres_database
    - triplea.infra.flyway
    - triplea.infra.service_systemctl_conf
    - nginx_conf
